github-actions: skip building on windows
Due to error building uWebSockets in both windows-2016 and
windows-2019:

fatal error C1189: #error:  The C++ Standard Library forbids
macroizing keywords. Enable warning C4005 to find the forbidden
macro.

Signed-off-by: Daniel Lundborg <daniel.lundborg@sandvik.com>